# Generated by Django 5.2.7 on 2025-10-20 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_clientprofile_freelancerprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientprofile",
            name="bio",
            field=models.CharField(default="null", max_length=255),
            preserve_default=False,
        ),
    ]
