# Generated by Django 5.2.7 on 2025-10-27 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_clientprofile_bio"),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        choices=[
                            ("web_development", "Web Development"),
                            ("app_development", "App Development"),
                            ("data_analysis", "Data Analysis"),
                            ("graphic_design", "Graphic Design"),
                            ("advertising", "Advertising"),
                            ("writing_and_translation", "Writing And Translation"),
                        ],
                        max_length=55,
                    ),
                ),
                ("description", models.TextField()),
                ("category", models.CharField(max_length=100)),
                ("budget_min", models.DecimalField(decimal_places=2, max_digits=10)),
                ("budget_max", models.DecimalField(decimal_places=2, max_digits=10)),
                ("deadline", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "skills_required",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.clientprofile",
                    ),
                ),
                (
                    "selected_freelancer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="awarded_projects",
                        to="app.freelancerprofile",
                    ),
                ),
            ],
        ),
    ]
