# Generated by Django 5.2.7 on 2025-10-27 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_project"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="category",
            field=models.CharField(
                choices=[
                    ("web_development", "Web Development"),
                    ("app_development", "App Development"),
                    ("data_analysis", "Data Analysis"),
                    ("graphic_design", "Graphic Design"),
                    ("advertising", "Advertising"),
                    ("writing_and_translation", "Writing And Translation"),
                ],
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="title",
            field=models.CharField(max_length=55),
        ),
    ]
